Error about missing loop when calling functions requiring a loop in the `finally` clause of a task
